name: todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # UPDATED versions (compatible)
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

# ---------------- APP ICON ----------------
flutter_launcher_icons:
  android: true
  ios: true

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/iron_fist.jpeg
  image_path: assets/iron_fist.jpeg

# ---------------- SPLASH SCREEN ----------------
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/iron_fist.jpeg

  android_12:
    color: "#FFFFFF"
    image: assets/iron_fist.jpeg

  fullscreen: true

# ---------------- FLUTTER ----------------
flutter:
  uses-material-design: true

  assets:
    - assets/iron_fist.jpeg

